version: '3.4'

services:
  elasticsearch: 
    image: docker.io/elasticsearch:8.15.3
    ports:
     - 9200:9200
    volumes:
      -  elasticsearch-data:/usr/share/elasticsearch/data
    environment:
     - xpack.security.enabled=false
     - discovery.type=single-node
  kibana:
    image: docker.io/kibana:8.15.3
    depends_on:
    - elasticsearch
    ports:
    - 5601:5601
    environment:
     - ELASTICSEARCH_URL=http://elasticsearch:9200
  prometheus:
    image: docker.io/prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    depends_on:
    - message_broker
    - database 
    - elasticsearch
  database:
      container_name: database-postgres
      image: ${DOCKER_REGISTRY-}postgres
      environment:
           - POSTGRES_USER=postgresRU
           - POSTGRES_PASSWORD=rtps
      ports:
        - "5432:5432"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
     ALLOW_ANONYMOUS_LOGIN: yes
  message_broker:
      image: docker.io/bitnami/kafka
      ports:
      - "9092:9092"
      environment:
       KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
       KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://message_broker:9092
       KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      depends_on:
      - zookeeper
  kafka_ui:
      container_name: kafka-ui
      image: docker.io/provectuslabs/kafka-ui
      ports:
      - "9100:8080"
      environment:
        KAFKA_CLUSTERS_0_NAME: transitional_path
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: message_broker:9092
        KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
        KAFKA_CLUSTERS_0_JMXPORT: 9997
        DYNAMIC_CONFIG_ENABLED: true
      depends_on: 
      - message_broker
  mailservice:
    image: ${DOCKER_REGISTRY-}mailservice
    build:
      context: .
      dockerfile: MailService/Dockerfile
    depends_on:
     - notificationservice
  smsservice:
    image: ${DOCKER_REGISTRY-}smsservice
    build:
      context: .
      dockerfile: SmsService/Dockerfile
    depends_on:
     - notificationservice
  pushservice:
    image: ${DOCKER_REGISTRY-}pushservice
    build:
      context: .
      dockerfile: PushService/Dockerfile
    depends_on:
     - notificationservice

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data    
  elasticsearch-data:
  





